DIRSDL=/users/prog1a/C/librairie/2011
CFLAGS=-g -c -I$(DIRSDL)/include -I$(DIRSDL)/include/SDL -I/usr/local/include -I/usr/local/include/SDL -I/usr/include/SDL
LDFLAGS=-L$(DIRSDL)/lib -lSDL -lSDL_ttf -lSDL_image  -lSDL_sound -lSDL_phelma -lSDL_draw -lX11


all : exemple demo5

exemple:exemple.o file.o pile.o carte.o  liste.o distribution.o graph2_visu.o
	gcc -o $@  $^  $(LDFLAGS)

demo5: demo5.o file.o pile.o carte.o  liste.o distribution.o graph2_visu.o
	gcc -o $@  $^  $(LDFLAGS)

%.o:%.c carte.h
	gcc $(CFLAGS) $<  -D MODEGRAPHIQUE


clean:
	rm *.o 


